plugins {
    id 'java'
}

ext {
    undertowVersion = '2.3.20.Final'
    jacksonVersion = '2.17.0'
    h2DatabaseVersion = '2.2.224'
    slf4jVersion = '2.0.13'
    commonsLangVersion = '3.18.0'
    junitVersion = '4.13.1'
    assertVersion = '3.26.0'
    mockitoVersion = '5.11.0'
    restAssuredVersion = '5.5.6'
}

group = 'com.api.account'
version = '1.0.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "io.undertow:undertow-core:${undertowVersion}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    implementation "com.h2database:h2:${h2DatabaseVersion}"
    implementation "org.slf4j:slf4j-api:${slf4jVersion}"
    implementation "org.slf4j:slf4j-simple:${slf4jVersion}"
    implementation "org.apache.commons:commons-lang3:${commonsLangVersion}"
    testImplementation "junit:junit:${junitVersion}"
    testImplementation "org.assertj:assertj-core:${assertVersion}"
    testImplementation "org.mockito:mockito-core:${mockitoVersion}"
    testImplementation "io.rest-assured:rest-assured:${restAssuredVersion}"
}
